//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBD_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUTHUE
    {
        public string MABANG { get; set; }
        public string SOPHIEUTHUE { get; set; }
        public Nullable<System.DateTime> NGAYTHUE { get; set; }
        public string DATRATIENTHUE { get; set; }
    
        public virtual BANG BANG { get; set; }
        public virtual PHIEUTHUE PHIEUTHUE { get; set; }
    }
}
