//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBD_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBDEntities : DbContext
    {
        public QLBDEntities()
            : base("name=QLBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANG> BANG { get; set; }
        public virtual DbSet<CHITIETPHIEUTHUE> CHITIETPHIEUTHUE { get; set; }
        public virtual DbSet<KHACH> KHACH { get; set; }
        public virtual DbSet<PHIEUTHUE> PHIEUTHUE { get; set; }
        public virtual DbSet<PHIM> PHIM { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<THELOAI> THELOAI { get; set; }
    }
}
