//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBD_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUTHUE()
        {
            this.CHITIETPHIEUTHUE = new HashSet<CHITIETPHIEUTHUE>();
        }
    
        public string SOPHIEUTHUE { get; set; }
        public string MAKHACH { get; set; }
        public Nullable<System.DateTime> NGAYTHUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUTHUE> CHITIETPHIEUTHUE { get; set; }
        public virtual KHACH KHACH { get; set; }
    }
}
