//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBD_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIM()
        {
            this.BANG = new HashSet<BANG>();
        }
    
        public string MAPHIM { get; set; }
        public string TENPHIM { get; set; }
        public string NUOCSX { get; set; }
        public string PHIMBOLE { get; set; }
        public Nullable<int> GIAVON { get; set; }
        public string MATHELOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG> BANG { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
